on:
  pull_request:

name: Integration

jobs:
  integration_test:
    name: Integration Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      checks: write
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT }}

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v2